import { readFile } from 'node:fs/promises'
import assert from 'node:assert/strict'

const installer = await readFile(new URL('../server/remote/agentInstaller.ts', import.meta.url), 'utf8')
const agentRoutes = await readFile(new URL('../server/routes/agentMetrics.ts', import.meta.url), 'utf8')
const hostRoutes = await readFile(new URL('../server/routes/hosts.ts', import.meta.url), 'utf8')
const hostData = await readFile(new URL('../server/data/hosts.ts', import.meta.url), 'utf8')
const serverTypes = await readFile(new URL('../server/types/host.ts', import.meta.url), 'utf8')
const srcTypes = await readFile(new URL('../src/types/host.ts', import.meta.url), 'utf8')
const jobPanel = await readFile(new URL('../src/components/hosts/AgentJobPanel.tsx', import.meta.url), 'utf8')
const hostDetail = await readFile(new URL('../src/pages/HostDetail.tsx', import.meta.url), 'utf8')
const hostsPage = await readFile(new URL('../src/pages/Hosts.tsx', import.meta.url), 'utf8')

assert.match(installer, /export const AGENT_VERSION = 'v2\.10\.12'/, 'agent version should be bumped for self-update rollout')
assert.match(installer, /OPS_AGENT_SELF_UPDATE_MARKER/, 'agent packages should include a self-update validation marker')
assert.match(installer, /export function buildAgentUpdatePackage/, 'server should build agent update packages')
assert.match(installer, /def perform_update_job\(job\):/, 'linux agent should support self-update jobs')
assert.match(installer, /systemctl restart ops-platform-agent/, 'linux self-update should restart the service after reporting success')
assert.match(installer, /function Invoke-AgentUpdateJob\(\$job\)/, 'windows agent should support self-update jobs')
assert.match(installer, /update-package\?os=Windows/, 'windows agent should fetch update packages via authenticated agent API')
assert.match(installer, /function Write-AgentUpdater\(\$targetVersion, \$tempPath, \$scriptPath, \$jobId\)/, 'windows self-update should be delegated to a detached updater')
assert.match(installer, /function Install-AgentUpdatePackage\(\$targetVersion, \$tempPath, \$scriptPath\)/, 'windows self-update should first try an in-process script replacement')
assert.match(installer, /Install-AgentUpdatePackage \$targetVersion \$tempPath \$scriptPath/, 'windows self-update should use the direct replacement path before detached fallback')
assert.match(installer, /Start-Process -FilePath 'powershell\.exe'/, 'windows self-update should start the detached updater outside the running agent process')
assert.match(installer, /Move-Item -LiteralPath \$tempPath -Destination \$scriptPath -Force/, 'windows updater should replace the agent script after the current run exits')
assert.match(installer, /Post-Json "\/api\/agent\/hosts\/\$\(.*?\)\/jobs\/\$\(.*?\)\/result" @\{ success = \$success;/, 'windows self-update should always post a job result instead of leaving scheduled jobs running')
assert.match(agentRoutes, /\/hosts\/:id\/update-package/, 'agent API should expose an authenticated update package endpoint')
assert.match(agentRoutes, /type: \{ in: \['start_service', 'stop_service', 'restart_service', 'batch_run_script', 'update_agent'\] \}/, 'agent polling should include update_agent jobs')
assert.match(agentRoutes, /job\.type === 'update_agent'/, 'agent result endpoint should handle update_agent jobs')
assert.match(agentRoutes, /Legacy Windows Agent self-update is disabled/, 'agent polling should fail legacy Windows self-update jobs instead of leaving them stuck')
assert.match(agentRoutes, /WINDOWS_SELF_UPDATE_MIN_AGENT_VERSION = 'v2\.10\.11'/, 'windows self-update gate should allow v2.10.11+ agents to update to newer versions')
assert.match(agentRoutes, /isAgentVersionAtLeast\(auth\.host\.agentVersion, WINDOWS_SELF_UPDATE_MIN_AGENT_VERSION\)/, 'windows self-update gate should use the fixed minimum reliable version, not the target rollout version')
assert.match(agentRoutes, /async function recoverStaleUpdateJobForHost/, 'agent polling should recover stale running update jobs')
assert.match(agentRoutes, /await recoverStaleUpdateJobForHost\(auth\.host\.id\)/, 'agent polling should run stale update recovery before selecting the next job')
assert.match(agentRoutes, /agentVersion: version/, 'successful update result should persist the reported version')
assert.match(hostData, /export async function queueAgentUpdateJobs/, 'host data layer should queue agent update jobs')
assert.match(hostData, /export async function recoverStaleAgentUpdateJobs/, 'host data layer should recover stale running update jobs')
assert.match(hostData, /type: 'update_agent'/, 'queued host jobs should use update_agent type')
assert.match(hostData, /agentTokenHash/, 'queueing should require an enrolled agent token')
assert.match(hostData, /SELF_UPDATE_MIN_AGENT_VERSION = 'v2\.10\.8'/, 'queueing should skip agents that do not yet support self-update')
assert.match(hostData, /AGENT_UPDATE_RUNNING_TIMEOUT_MS/, 'queueing should enforce a timeout for running update jobs')
assert.match(hostData, /status: 'failed'[\s\S]*Agent update job timed out/, 'stale running update jobs should be marked failed before requeueing')
assert.match(hostRoutes, /\/agent-update-jobs/, 'host API should expose batch agent update queueing')
assert.match(serverTypes, /'update_agent'/, 'server AgentJobType should include update_agent')
assert.match(srcTypes, /'update_agent'/, 'client AgentJobType should include update_agent')
assert.match(jobPanel, /update_agent: '更新 Agent'/, 'job history should label update_agent jobs')
assert.match(hostDetail, /更新 Agent/, 'host detail should expose an Agent update action')
assert.match(hostsPage, /批量更新 Agent/, 'host list should expose a bulk Agent update action')

console.log('agent-self-update-ok')
