import { readFile } from 'node:fs/promises'
import assert from 'node:assert/strict'

const source = await readFile(new URL('../server/remote/agentInstaller.ts', import.meta.url), 'utf8')
const linuxSource = source.match(/cat >\/usr\/local\/bin\/ops-platform-agent <<'PY'\n([\s\S]*?)\nPY/)?.[1] ?? ''
const windowsSource = source

assert.match(source, /export const AGENT_VERSION = 'v2\.10\.5'/, 'agent version should be bumped for reinstall verification')
assert.match(source, /def post_log_batches\(logs\):/, 'linux agent should upload logs in 100-row batches')
assert.match(source, /function Post-LogBatches\(\$logs\)/, 'windows agent should upload logs in 100-row batches')
assert.doesNotMatch(source, /\['docker', 'logs', '--timestamps', '--tail', '80'\]/, 'docker logs should not always be limited to the last 80 rows')
assert.match(source, /command = \['docker', 'logs', '--timestamps'\]/, 'docker logs should start with timestamps and add tail only for initial backfill')
assert.match(source, /command\.extend\(\['--since', since\]\)/, 'docker logs should resume from saved checkpoint')
assert.match(source, /log_level\(message, 'INFO'\)/, 'plain container log lines should default to INFO')
assert.match(source, /trace_basis = key \+ ':' \+ str\(line_start\) \+ ':' \+ message/, 'linux file trace id should include offset')
assert.doesNotMatch(source, /SHA1\]::HashData/, 'windows agent should avoid PowerShell 7-only SHA1.HashData')
assert.doesNotMatch(source, /Convert\]::ToHexString/, 'windows agent should avoid PowerShell 7-only Convert.ToHexString')
assert.match(source, /function Get-Sha1Hex\(\$text\)/, 'windows agent should use a PowerShell-compatible SHA1 helper')
assert.doesNotMatch(windowsSource, /\.Dispose\(\)/, 'windows agent should avoid Dispose calls that fail on PowerShell 2 crypto objects')
assert.match(source, /FileShare\]::ReadWrite -bor \[System\.IO\.FileShare\]::Delete/, 'windows log files should be opened with delete sharing for rotation')
assert.match(windowsSource, /function Get-OpsBusinessNow/, 'windows configured log dates should use the platform business timezone')
assert.match(windowsSource, /ToUniversalTime\(\)\.AddHours\(8\)/, 'windows configured log dates should use Beijing UTC+8 instead of remote local date')
assert.match(source, /function Get-ConfiguredLogFiles\(\$pathValue\)/, 'windows configured paths should use the configured-file discovery helper')
assert.doesNotMatch(windowsSource, /function Is-LogLikeFile\(\$item\)/, 'windows configured directory logs should not require specific filename extensions')
assert.doesNotMatch(windowsSource, /@\('\.log', '\.txt'\) -notcontains \$item\.Extension/, 'windows configured directory logs should accept any suffix when the filename has today date')
assert.doesNotMatch(windowsSource, /LastWriteTime\.Date -eq \$today/, 'windows configured directory logs should require today date in the filename, not only modification time')
assert.doesNotMatch(source, /function Get-TodayLogFiles/, 'windows configured directory logs should not be limited to today-only files')
assert.doesNotMatch(source, /finally:\n\s+save_state\(state\)/, 'linux agent should not persist advanced offsets in a finally block after failed upload')
assert.doesNotMatch(source, /finally \{\n\s+Save-State \$state\n\s+\}/, 'windows agent should not persist advanced offsets in a finally block after failed upload')
assert.doesNotMatch(linuxSource, /systemctl', 'list-units/, 'linux agent should not collect ordinary systemd services')
assert.doesNotMatch(linuxSource, /\/services'/, 'linux agent should not post ordinary service snapshots')
assert.doesNotMatch(linuxSource, /\/service-events'/, 'linux agent should not post ordinary service events')
assert.match(linuxSource, /def discover_containers\(\):/, 'linux agent should keep Docker container discovery')
assert.match(linuxSource, /'docker', 'ps'/, 'linux agent should keep Docker ps collection')
assert.match(linuxSource, /'docker', 'inspect'/, 'linux agent should keep Docker inspect collection')
assert.match(linuxSource, /'docker', 'stats'/, 'linux agent should keep Docker stats collection')
assert.match(linuxSource, /\/containers'/, 'linux agent should keep posting Docker containers')
assert.match(linuxSource, /read_container_logs\(containers, state\)/, 'linux agent should keep Docker log collection')
assert.match(windowsSource, /function Collect-Services/, 'windows agent should keep Windows service collection')
assert.match(windowsSource, /\/services"/, 'windows agent should keep posting Windows services')
assert.match(windowsSource, /\/service-events"/, 'windows agent should keep posting Windows service events')
assert.match(windowsSource, /Get-WinEvent -LogName \$logName -MaxEvents 500/, 'windows agent should collect a larger Windows Event Log window')
assert.match(windowsSource, /Get-EventLog -LogName \$logName -Newest 500/, 'windows agent should fall back to larger legacy Event Log collection for Windows 2008')
assert.match(windowsSource, /function ConvertTo-OpsJson\(\$value\)/, 'windows agent should not require ConvertTo-Json on old PowerShell')
assert.match(windowsSource, /function ConvertFrom-SimpleJson\(\$text\)/, 'windows agent should parse simple JSON without ConvertFrom-Json or System.Web.Extensions')
assert.match(windowsSource, /HttpWebRequest/, 'windows agent should not require Invoke-RestMethod on old PowerShell')
assert.doesNotMatch(windowsSource, /Get-ChildItem -LiteralPath \$pathValue -File/, 'windows agent should avoid PowerShell 3-only Get-ChildItem -File')
assert.match(windowsSource, /Get-WmiObject -Class Win32_Process -Filter "name = 'powershell\.exe'"/, 'windows reinstall should use explicit WMI class syntax when stopping old agent processes')
assert.match(windowsSource, /foreach \(\$logName in @\('System', 'Application'\)\)/, 'windows agent should default to System and Application event logs')
assert.doesNotMatch(windowsSource, /Level -notin @\(1, 2\)/, 'windows event logs should not be limited to ERROR events')
assert.match(windowsSource, /function Get-EventLogLevel\(\$event\)/, 'windows agent should map Event Log levels to platform levels')
assert.match(windowsSource, /3 \{ return 'WARN' \}/, 'windows warning events should map to WARN')
assert.match(windowsSource, /5 \{ return 'DEBUG' \}/, 'windows verbose events should map to DEBUG')
assert.match(windowsSource, /levelDisplayName/, 'windows event labels should include level display name')

console.log('agent-installer-template-regression-ok')
