import { readFile } from 'node:fs/promises'
import assert from 'node:assert/strict'

const serverTime = await readFile(new URL('../server/utils/time.ts', import.meta.url), 'utf8')
const agentAuth = await readFile(new URL('../server/utils/agentAuth.ts', import.meta.url), 'utf8')
const hostAudit = await readFile(new URL('../server/utils/audit.ts', import.meta.url), 'utf8')
const alerts = await readFile(new URL('../server/data/alerts.ts', import.meta.url), 'utf8')
const auditLogs = await readFile(new URL('../server/data/auditLogs.ts', import.meta.url), 'utf8')
const users = await readFile(new URL('../server/data/users.ts', import.meta.url), 'utf8')
const notifications = await readFile(new URL('../server/services/notificationService.ts', import.meta.url), 'utf8')
const frontendTime = await readFile(new URL('../src/utils/time.ts', import.meta.url), 'utf8')
const hostDetail = await readFile(new URL('../src/pages/HostDetail.tsx', import.meta.url), 'utf8')
const logMonitoring = await readFile(new URL('../src/pages/LogMonitoring.tsx', import.meta.url), 'utf8')
const cgiMonitor = await readFile(new URL('../src/components/log-monitoring/CgiMonitorPanel.tsx', import.meta.url), 'utf8')
const hostResourceMonitor = await readFile(new URL('../src/components/log-monitoring/HostResourceMonitorPanel.tsx', import.meta.url), 'utf8')
const sslPage = await readFile(new URL('../src/pages/SslCertificateMonitor.tsx', import.meta.url), 'utf8')
const aiPage = await readFile(new URL('../src/pages/AIAssistant.jsx', import.meta.url), 'utf8')

assert.match(serverTime, /timeZone: 'Asia\/Shanghai'/, 'server time helper should use Beijing timezone')
assert.match(serverTime, /export function shanghaiTime/, 'server should expose a Beijing time formatter')
assert.match(serverTime, /export function startOfShanghaiDayUtc/, 'server should calculate Beijing day boundaries')
assert.match(agentAuth, /lastHeartbeat: shanghaiTime\(new Date\(\)\)/, 'agent heartbeat text should use Beijing time')
assert.match(hostAudit, /time: shanghaiTime\(new Date\(\)\)/, 'host audit time should use Beijing time')
assert.match(alerts, /return shanghaiTime\(new Date\(\)\)/, 'alert action timestamps should use Beijing time')
assert.match(alerts, /startOfShanghaiDayUtc/, 'alert today summary should use Beijing day boundary')
assert.match(auditLogs, /createdAt: shanghaiTime\(now\)/, 'audit export task timestamps should use Beijing time')
assert.match(users, /return shanghaiTime\(date\)/, 'account timestamps should use Beijing time')
assert.match(notifications, /createdAt: shanghaiTime\(row\.createdAt\)/, 'notification timestamps should use Beijing time')
assert.match(frontendTime, /timeZone: 'Asia\/Shanghai'/, 'frontend formatter should use Beijing timezone')
assert.doesNotMatch(hostDetail, /new Date\(selectedHost\.maintenance\.until\)\.toLocaleString/, 'host detail should not format maintenance time with default timezone')
assert.match(logMonitoring, /formatShanghaiTime\(rule\.lastTriggeredAt\)/, 'log monitor list should format trigger time as Beijing time')
assert.match(cgiMonitor, /formatShanghaiTime\(rule\.lastTriggeredAt\)/, 'CGI monitor list should format trigger time as Beijing time')
assert.match(hostResourceMonitor, /return formatShanghaiTime\(value\)/, 'host resource monitor should format dates as Beijing time')
assert.match(sslPage, /return formatShanghaiTime\(value\)/, 'SSL page should format dates as Beijing time')
assert.match(aiPage, /return formatShanghaiTime\(value\)/, 'AI health report page should format dates as Beijing time')

console.log('beijing-time-display-ok')
