import { readFile } from 'node:fs/promises'
import assert from 'node:assert/strict'

const batchData = await readFile(new URL('../server/data/batchJobs.ts', import.meta.url), 'utf8')
const agentRoutes = await readFile(new URL('../server/routes/agentMetrics.ts', import.meta.url), 'utf8')
const installer = await readFile(new URL('../server/remote/agentInstaller.ts', import.meta.url), 'utf8')
const page = await readFile(new URL('../src/pages/BatchJobs.tsx', import.meta.url), 'utf8')
const jobPanel = await readFile(new URL('../src/components/hosts/AgentJobPanel.tsx', import.meta.url), 'utf8')

assert.match(batchData, /type: 'batch_run_script'/, 'Windows batch scripts should create Agent jobs')
assert.match(batchData, /scriptBase64: Buffer\.from\(script, 'utf8'\)\.toString\('base64'\)/, 'batch script payload should be base64 encoded for safe JSON transport')
assert.match(batchData, /type: 'batch_file_operation'/, 'Windows batch file operations should create Agent jobs')
assert.match(batchData, /WINDOWS_BATCH_FILE_MIN_AGENT_VERSION = 'v2\.10\.18'/, 'backend should require complete Windows file-transfer support')
assert.match(batchData, /fileContentBase64: content !== undefined \? content\.toString\('base64'\) : undefined/, 'Windows upload payload should preserve zero-byte file content')
assert.match(batchData, /completeWindowsBatchFileAgentResult/, 'Windows file operation results should be ingested into batch targets')
assert.match(batchData, /WINDOWS_BATCH_JOB_TIMEOUT_MS = 5 \* 60 \* 1000/, 'Windows Agent batch jobs should have a bounded callback timeout')
assert.match(batchData, /export async function recoverStaleWindowsBatchJobs/, 'stale Windows Agent batch jobs should be recoverable')
assert.match(batchData, /exitCode: 124/, 'timed out Windows Agent batch targets should expose a timeout exit code')
assert.match(batchData, /Windows 主机 Agent 未在线或未正常/, 'Windows Agent readiness should be validated before queuing scripts')
assert.match(agentRoutes, /batch_run_script/, 'Agent polling endpoint should support batch script jobs')
assert.match(agentRoutes, /batch_file_operation/, 'Agent polling endpoint should support file operation jobs')
assert.match(agentRoutes, /batchJobTarget\.updateMany/, 'Agent result endpoint should update batch target rows')
assert.match(installer, /function Invoke-BatchScriptJob\(\$job\)/, 'Windows Agent should execute batch script jobs')
assert.match(installer, /function Invoke-BatchFileJob\(\$job\)/, 'Windows Agent should execute batch file jobs')
assert.match(installer, /Get-FileMd5Hex/, 'Windows Agent should calculate MD5 locally')
assert.match(installer, /FromBase64String\(\$scriptBase64\)/, 'Windows Agent should decode script payload from base64')
assert.doesNotMatch(installer, /\$\{timeoutSeconds\}/, 'PowerShell timeout variable should not be interpolated by the TypeScript template')
assert.match(page, /Agent 通道/, 'Batch UI should label Windows script targets as Agent channel')
assert.match(page, /Agent 文件通道/, 'Batch UI should label Windows file targets as Agent file channel')
assert.match(page, /WINDOWS_BATCH_FILE_MIN_AGENT_VERSION = 'v2\.10\.18'/, 'Batch UI should use the same minimum Windows Agent version as the backend')
assert.match(page, /isAgentVersionAtLeast\(host\.agentVersion, WINDOWS_BATCH_FILE_MIN_AGENT_VERSION\)/, 'Batch UI should disable Windows file targets with unsupported Agent versions')
assert.match(page, /const \[selectedFile, setSelectedFile\] = useState<File>\(\)/, 'Batch UI should retain the raw file selected by Ant Design 6')
assert.match(page, /const originFile = selectedFile \?\? fileList\[0\]\?\.originFileObj/, 'Batch upload should prefer the retained raw file and keep originFileObj compatibility')
assert.match(page, /fileContentBase64: await fileToBase64\(originFile\)/, 'Batch upload should include the selected file content in the API payload')
assert.match(page, /beforeUpload=\{\(file\) => \{[\s\S]*setSelectedFile\(file\)[\s\S]*return false/, 'Batch Upload beforeUpload should retain the raw File object')
assert.match(jobPanel, /batch_run_script: '批处理脚本'/, 'Agent job history should label batch script jobs')
assert.match(jobPanel, /batch_file_operation: '批处理文件'/, 'Agent job history should label batch file jobs')

console.log('windows-batch-agent-channel-ok')
