export const PERMISSIONS = {
    DASHBOARD_VIEW: 'dashboard:view',
    ALERTS_VIEW: 'alerts:view',
    LOGS_VIEW: 'logs:view',
    TOPOLOGY_VIEW: 'topology:view',
    HOSTS_VIEW: 'hosts:view',
    HOSTS_MANAGE: 'hosts:manage',
    HOSTS_AGENT: 'hosts:agent',
    HOSTS_DELETE: 'hosts:delete',
    ACCOUNTS_MANAGE: 'accounts:manage',
    AUDIT_LOG_VIEW: 'audit_log_view',
    INTERNAL_VIEW: 'internal:view',
    SELF_HEALING_VIEW: 'self_healing_view',
    SELF_HEALING_MANAGE: 'self_healing_manage',
    AI_VIEW: 'ai:view',
    INSPECTION_VIEW: 'inspection:view',
    SETTINGS_VIEW: 'settings:view',
};
export const ROLE_LABELS = {
    admin: '平台管理员',
    sre: 'SRE 工程师',
    auditor: '审计员',
    viewer: '只读用户',
};
const allPermissions = Object.values(PERMISSIONS);
export const ROLE_PERMISSIONS = {
    admin: allPermissions,
    sre: [
        PERMISSIONS.DASHBOARD_VIEW,
        PERMISSIONS.ALERTS_VIEW,
        PERMISSIONS.LOGS_VIEW,
        PERMISSIONS.TOPOLOGY_VIEW,
        PERMISSIONS.HOSTS_VIEW,
        PERMISSIONS.HOSTS_MANAGE,
        PERMISSIONS.HOSTS_AGENT,
        PERMISSIONS.HOSTS_DELETE,
        PERMISSIONS.INTERNAL_VIEW,
        PERMISSIONS.SELF_HEALING_VIEW,
        PERMISSIONS.SELF_HEALING_MANAGE,
        PERMISSIONS.AI_VIEW,
        PERMISSIONS.INSPECTION_VIEW,
    ],
    auditor: [
        PERMISSIONS.DASHBOARD_VIEW,
        PERMISSIONS.ALERTS_VIEW,
        PERMISSIONS.LOGS_VIEW,
        PERMISSIONS.TOPOLOGY_VIEW,
        PERMISSIONS.HOSTS_VIEW,
        PERMISSIONS.AUDIT_LOG_VIEW,
        PERMISSIONS.SELF_HEALING_VIEW,
        PERMISSIONS.SETTINGS_VIEW,
    ],
    viewer: [
        PERMISSIONS.DASHBOARD_VIEW,
        PERMISSIONS.ALERTS_VIEW,
        PERMISSIONS.LOGS_VIEW,
        PERMISSIONS.TOPOLOGY_VIEW,
        PERMISSIONS.HOSTS_VIEW,
        PERMISSIONS.AI_VIEW,
    ],
};
